// <auto-generated />
using System;
using Enkl.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Enkl.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260719070950_AddChatReactions")]
    partial class AddChatReactions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Enkl.Api.Domain.Entities.ChatChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDirectMessage")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("OrganisationId");

                    b.ToTable("ChatChannels");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.ChatChannelMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ChannelId", "UserId")
                        .IsUnique();

                    b.ToTable("ChatChannelMembers");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("ChannelId");

                    b.HasIndex("DateCreated");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.ChatMessageReaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("MessageId", "UserId", "Emoji")
                        .IsUnique();

                    b.ToTable("ChatMessageReactions");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.Column", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(-1);

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("Done")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Columns");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.Decision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Approver")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Outcome")
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("TaskId");

                    b.HasIndex("ProjectId", "Key")
                        .IsUnique();

                    b.ToTable("Decisions");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.DecisionDocument", b =>
                {
                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.HasKey("DecisionId", "DocumentId");

                    b.HasIndex("DocumentId");

                    b.ToTable("DecisionDocument");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.DecisionObjective", b =>
                {
                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ObjectiveId")
                        .HasColumnType("uuid");

                    b.HasKey("DecisionId", "ObjectiveId");

                    b.HasIndex("ObjectiveId");

                    b.ToTable("DecisionObjective");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.DecisionPrinciple", b =>
                {
                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrincipleId")
                        .HasColumnType("uuid");

                    b.HasKey("DecisionId", "PrincipleId");

                    b.HasIndex("PrincipleId");

                    b.ToTable("DecisionPrinciple");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.DecisionRisk", b =>
                {
                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RiskId")
                        .HasColumnType("uuid");

                    b.HasKey("DecisionId", "RiskId");

                    b.HasIndex("RiskId");

                    b.ToTable("DecisionRisk");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("TaskId");

                    b.HasIndex("ProjectId", "Key")
                        .IsUnique();

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.DocumentRelation", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RelatedDocumentId")
                        .HasColumnType("uuid");

                    b.HasKey("DocumentId", "RelatedDocumentId");

                    b.HasIndex("RelatedDocumentId");

                    b.ToTable("DocumentRelation");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.Objective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Key")
                        .IsUnique();

                    b.ToTable("Objectives");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.ObjectivePrinciple", b =>
                {
                    b.Property<Guid>("ObjectiveId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrincipleId")
                        .HasColumnType("uuid");

                    b.HasKey("ObjectiveId", "PrincipleId");

                    b.HasIndex("PrincipleId");

                    b.ToTable("ObjectivePrinciple");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.OrgTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScimExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId", "ScimExternalId")
                        .IsUnique()
                        .HasFilter("\"ScimExternalId\" IS NOT NULL");

                    b.ToTable("OrgTeams");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.OrgTeamMember", b =>
                {
                    b.Property<Guid>("OrgTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("OrgTeamId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("OrgTeamMember");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.OrganisationApiKey", b =>
                {
                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KeyHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OrganisationId");

                    b.ToTable("OrganisationApiKeys");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.OrganisationSsoConfig", b =>
                {
                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdpEntityId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IdpSigningCertificate")
                        .HasColumnType("text");

                    b.Property<string>("IdpSsoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("RequireSso")
                        .HasColumnType("boolean");

                    b.Property<bool>("SamlEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("SamlJitProvisioning")
                        .HasColumnType("boolean");

                    b.Property<string>("ScimBearerTokenHash")
                        .HasColumnType("text");

                    b.Property<bool>("ScimEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ScimTokenGeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ScimTokenLastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OrganisationId");

                    b.ToTable("OrganisationSsoConfigs");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.PageLoadTiming", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("DurationMs")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAt");

                    b.ToTable("PageLoadTimings");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.PortfolioCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.ToTable("PortfolioCategories");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.Principle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DocumentUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsOrganisationWide")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId", "IsOrganisationWide");

                    b.HasIndex("ProjectId", "Key")
                        .IsUnique();

                    b.ToTable("Principles");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateLastExported")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("HeaderButtonVisibilityJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("medium");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("TaskCounter")
                        .HasColumnType("integer");

                    b.Property<string>("WorkflowJson")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OrganisationId", "Key")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.ProjectMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AllocatedFraction")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsProjectAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReportsToId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReportsToId");

                    b.HasIndex("UserId");

                    b.HasIndex("ProjectId", "UserId")
                        .IsUnique();

                    b.ToTable("ProjectMembers");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.ProjectResourcePlaceholder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AllocatedFraction")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectResourcePlaceholders");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.ProjectTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ColumnsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TaskTypesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("WorkflowJson")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.ToTable("ProjectTemplates");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.Release", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Releases");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.Retrospective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Background")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("LastTimerDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReleaseId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("RetroDate")
                        .HasColumnType("date");

                    b.Property<string>("Team")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseId");

                    b.HasIndex("ProjectId", "Key")
                        .IsUnique();

                    b.ToTable("Retrospectives");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.RetrospectiveActionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RetrospectiveId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("RetrospectiveId");

                    b.ToTable("RetrospectiveActionItems");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.RetrospectiveItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Column")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PromotedPrincipleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RetrospectiveId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("PromotedPrincipleId");

                    b.HasIndex("RetrospectiveId");

                    b.ToTable("RetrospectiveItems");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.RetrospectiveParticipant", b =>
                {
                    b.Property<Guid>("RetrospectiveId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectMemberId")
                        .HasColumnType("uuid");

                    b.HasKey("RetrospectiveId", "ProjectMemberId");

                    b.HasIndex("ProjectMemberId");

                    b.ToTable("RetrospectiveParticipants");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.Risk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("DateClosed")
                        .HasColumnType("date");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateToClose")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Impact")
                        .HasColumnType("integer");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Likelihood")
                        .HasColumnType("integer");

                    b.Property<string>("Mitigations")
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("TaskId");

                    b.HasIndex("ProjectId", "Key")
                        .IsUnique();

                    b.ToTable("Risks");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.RiskDocument", b =>
                {
                    b.Property<Guid>("RiskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.HasKey("RiskId", "DocumentId");

                    b.HasIndex("DocumentId");

                    b.ToTable("RiskDocument");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.RiskObjective", b =>
                {
                    b.Property<Guid>("RiskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ObjectiveId")
                        .HasColumnType("uuid");

                    b.HasKey("RiskId", "ObjectiveId");

                    b.HasIndex("ObjectiveId");

                    b.ToTable("RiskObjective");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.RiskPrinciple", b =>
                {
                    b.Property<Guid>("RiskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrincipleId")
                        .HasColumnType("uuid");

                    b.HasKey("RiskId", "PrincipleId");

                    b.HasIndex("PrincipleId");

                    b.ToTable("RiskPrinciple");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.SavedQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ExposeViaApi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sql")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("SavedQueries");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.TaskAuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskAuditLogEntries");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.TaskComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskComments");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.TaskDependency", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DependsOnTaskId")
                        .HasColumnType("uuid");

                    b.HasKey("TaskId", "DependsOnTaskId");

                    b.HasIndex("DependsOnTaskId");

                    b.ToTable("TaskDependencies");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ActualEffort")
                        .HasColumnType("numeric");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid");

                    b.Property<int?>("BusinessValue")
                        .HasColumnType("integer");

                    b.Property<Guid>("ColumnId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDone")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DocumentationUrl")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("EstimatedEffort")
                        .HasColumnType("numeric");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("ParentTaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReleaseId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int?>("TaskCost")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("TypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("ColumnId");

                    b.HasIndex("ParentTaskId");

                    b.HasIndex("ReleaseId");

                    b.HasIndex("TypeId");

                    b.HasIndex("ProjectId", "Key")
                        .IsUnique();

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.TaskType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IconName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("TaskTypes");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.TeamCommittee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceOrgTeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("SourceOrgTeamId");

                    b.HasIndex("ProjectId", "Key")
                        .IsUnique();

                    b.ToTable("TeamsCommittees");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.TeamCommitteeMember", b =>
                {
                    b.Property<Guid>("TeamCommitteeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectMemberId")
                        .HasColumnType("uuid");

                    b.HasKey("TeamCommitteeId", "ProjectMemberId");

                    b.HasIndex("ProjectMemberId");

                    b.ToTable("TeamCommitteeMember");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.ToDoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ToDoListId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ToDoListId");

                    b.ToTable("ToDoItems");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.ToDoList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ToDoLists");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsOrgAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedEmailAddress")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmailAddress")
                        .IsUnique();

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.HasIndex("OrganisationId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.ChatChannel", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Enkl.Api.Domain.Entities.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.ChatChannelMember", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.ChatChannel", "Channel")
                        .WithMany("Members")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Enkl.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.User", "AuthorUser")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Enkl.Api.Domain.Entities.ChatChannel", "Channel")
                        .WithMany("Messages")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorUser");

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.ChatMessageReaction", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.ChatMessage", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Enkl.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.Column", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.Project", "Project")
                        .WithMany("Columns")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.Decision", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.ProjectMember", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Enkl.Api.Domain.Entities.Project", "Project")
                        .WithMany("Decisions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Enkl.Api.Domain.Entities.TaskItem", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Owner");

                    b.Navigation("Project");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.DecisionDocument", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.Decision", "Decision")
                        .WithMany("Documents")
                        .HasForeignKey("DecisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Enkl.Api.Domain.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Decision");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.DecisionObjective", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.Decision", "Decision")
                        .WithMany("Objectives")
                        .HasForeignKey("DecisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Enkl.Api.Domain.Entities.Objective", "Objective")
                        .WithMany()
                        .HasForeignKey("ObjectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Decision");

                    b.Navigation("Objective");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.DecisionPrinciple", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.Decision", "Decision")
                        .WithMany("Principles")
                        .HasForeignKey("DecisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Enkl.Api.Domain.Entities.Principle", "Principle")
                        .WithMany()
                        .HasForeignKey("PrincipleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Decision");

                    b.Navigation("Principle");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.DecisionRisk", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.Decision", "Decision")
                        .WithMany("Risks")
                        .HasForeignKey("DecisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Enkl.Api.Domain.Entities.Risk", "Risk")
                        .WithMany()
                        .HasForeignKey("RiskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Decision");

                    b.Navigation("Risk");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.Document", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.ProjectMember", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Enkl.Api.Domain.Entities.Project", "Project")
                        .WithMany("Documents")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Enkl.Api.Domain.Entities.TaskItem", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Owner");

                    b.Navigation("Project");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.DocumentRelation", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.Document", "Document")
                        .WithMany("RelatedDocuments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Enkl.Api.Domain.Entities.Document", "RelatedDocument")
                        .WithMany()
                        .HasForeignKey("RelatedDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("RelatedDocument");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.Objective", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.Project", "Project")
                        .WithMany("Objectives")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.ObjectivePrinciple", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.Objective", "Objective")
                        .WithMany("Principles")
                        .HasForeignKey("ObjectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Enkl.Api.Domain.Entities.Principle", "Principle")
                        .WithMany()
                        .HasForeignKey("PrincipleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Objective");

                    b.Navigation("Principle");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.OrgTeam", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.Organisation", "Organisation")
                        .WithMany("OrgTeams")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.OrgTeamMember", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.OrgTeam", "OrgTeam")
                        .WithMany("Members")
                        .HasForeignKey("OrgTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Enkl.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrgTeam");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.OrganisationApiKey", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.Organisation", "Organisation")
                        .WithOne("ApiKey")
                        .HasForeignKey("Enkl.Api.Domain.Entities.OrganisationApiKey", "OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.OrganisationSsoConfig", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.Organisation", "Organisation")
                        .WithOne("SsoConfig")
                        .HasForeignKey("Enkl.Api.Domain.Entities.OrganisationSsoConfig", "OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.PortfolioCategory", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.Principle", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.Project", "Project")
                        .WithMany("Principles")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.Project", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.PortfolioCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Enkl.Api.Domain.Entities.Organisation", "Organisation")
                        .WithMany("Projects")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.ProjectMember", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.Project", "Project")
                        .WithMany("Members")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Enkl.Api.Domain.Entities.ProjectMember", "ReportsTo")
                        .WithMany()
                        .HasForeignKey("ReportsToId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Enkl.Api.Domain.Entities.User", "User")
                        .WithMany("ProjectMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("ReportsTo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.ProjectResourcePlaceholder", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Enkl.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.ProjectTemplate", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.Organisation", "Organisation")
                        .WithMany("ProjectTemplates")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.Release", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.ProjectMember", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Enkl.Api.Domain.Entities.Project", "Project")
                        .WithMany("Releases")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.Retrospective", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.Project", "Project")
                        .WithMany("Retrospectives")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Enkl.Api.Domain.Entities.Release", "Release")
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Project");

                    b.Navigation("Release");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.RetrospectiveActionItem", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.ProjectMember", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Enkl.Api.Domain.Entities.Retrospective", "Retrospective")
                        .WithMany("ActionItems")
                        .HasForeignKey("RetrospectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("Retrospective");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.RetrospectiveItem", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.Principle", "PromotedPrinciple")
                        .WithMany()
                        .HasForeignKey("PromotedPrincipleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Enkl.Api.Domain.Entities.Retrospective", "Retrospective")
                        .WithMany("Items")
                        .HasForeignKey("RetrospectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PromotedPrinciple");

                    b.Navigation("Retrospective");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.RetrospectiveParticipant", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.ProjectMember", "ProjectMember")
                        .WithMany()
                        .HasForeignKey("ProjectMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Enkl.Api.Domain.Entities.Retrospective", "Retrospective")
                        .WithMany("Participants")
                        .HasForeignKey("RetrospectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectMember");

                    b.Navigation("Retrospective");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.Risk", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.ProjectMember", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Enkl.Api.Domain.Entities.Project", "Project")
                        .WithMany("Risks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Enkl.Api.Domain.Entities.TaskItem", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Owner");

                    b.Navigation("Project");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.RiskDocument", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Enkl.Api.Domain.Entities.Risk", "Risk")
                        .WithMany("Documents")
                        .HasForeignKey("RiskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Risk");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.RiskObjective", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.Objective", "Objective")
                        .WithMany()
                        .HasForeignKey("ObjectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Enkl.Api.Domain.Entities.Risk", "Risk")
                        .WithMany("Objectives")
                        .HasForeignKey("RiskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Objective");

                    b.Navigation("Risk");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.RiskPrinciple", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.Principle", "Principle")
                        .WithMany()
                        .HasForeignKey("PrincipleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Enkl.Api.Domain.Entities.Risk", "Risk")
                        .WithMany("Principles")
                        .HasForeignKey("RiskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Principle");

                    b.Navigation("Risk");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.SavedQuery", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.Project", "Project")
                        .WithMany("SavedQueries")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.TaskAuditLogEntry", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.TaskItem", "Task")
                        .WithMany("AuditLog")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.TaskComment", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.ProjectMember", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Enkl.Api.Domain.Entities.TaskItem", "Task")
                        .WithMany("Comments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.TaskDependency", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.TaskItem", "DependsOnTask")
                        .WithMany()
                        .HasForeignKey("DependsOnTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Enkl.Api.Domain.Entities.TaskItem", "Task")
                        .WithMany("Dependencies")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DependsOnTask");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.ProjectMember", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Enkl.Api.Domain.Entities.Column", "Column")
                        .WithMany()
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Enkl.Api.Domain.Entities.TaskItem", "ParentTask")
                        .WithMany()
                        .HasForeignKey("ParentTaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Enkl.Api.Domain.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Enkl.Api.Domain.Entities.Release", "Release")
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Enkl.Api.Domain.Entities.TaskType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Assignee");

                    b.Navigation("Column");

                    b.Navigation("ParentTask");

                    b.Navigation("Project");

                    b.Navigation("Release");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.TaskType", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.Project", "Project")
                        .WithMany("TaskTypes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.TeamCommittee", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.TeamCommittee", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Enkl.Api.Domain.Entities.Project", "Project")
                        .WithMany("TeamsCommittees")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Enkl.Api.Domain.Entities.OrgTeam", "SourceOrgTeam")
                        .WithMany()
                        .HasForeignKey("SourceOrgTeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Parent");

                    b.Navigation("Project");

                    b.Navigation("SourceOrgTeam");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.TeamCommitteeMember", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.ProjectMember", "ProjectMember")
                        .WithMany()
                        .HasForeignKey("ProjectMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Enkl.Api.Domain.Entities.TeamCommittee", "TeamCommittee")
                        .WithMany("Members")
                        .HasForeignKey("TeamCommitteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectMember");

                    b.Navigation("TeamCommittee");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.ToDoItem", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.ToDoList", "ToDoList")
                        .WithMany("Items")
                        .HasForeignKey("ToDoListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToDoList");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.ToDoList", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.User", b =>
                {
                    b.HasOne("Enkl.Api.Domain.Entities.Organisation", "Organisation")
                        .WithMany("Users")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.ChatChannel", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.Decision", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Objectives");

                    b.Navigation("Principles");

                    b.Navigation("Risks");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.Document", b =>
                {
                    b.Navigation("RelatedDocuments");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.Objective", b =>
                {
                    b.Navigation("Principles");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.OrgTeam", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.Organisation", b =>
                {
                    b.Navigation("ApiKey");

                    b.Navigation("OrgTeams");

                    b.Navigation("ProjectTemplates");

                    b.Navigation("Projects");

                    b.Navigation("SsoConfig");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.Project", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("Decisions");

                    b.Navigation("Documents");

                    b.Navigation("Members");

                    b.Navigation("Objectives");

                    b.Navigation("Principles");

                    b.Navigation("Releases");

                    b.Navigation("Retrospectives");

                    b.Navigation("Risks");

                    b.Navigation("SavedQueries");

                    b.Navigation("TaskTypes");

                    b.Navigation("Tasks");

                    b.Navigation("TeamsCommittees");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.Retrospective", b =>
                {
                    b.Navigation("ActionItems");

                    b.Navigation("Items");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.Risk", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Objectives");

                    b.Navigation("Principles");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.TaskItem", b =>
                {
                    b.Navigation("AuditLog");

                    b.Navigation("Comments");

                    b.Navigation("Dependencies");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.TeamCommittee", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.ToDoList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Enkl.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("ProjectMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
